# Generated by Django 4.0.6 on 2025-04-07 12:33

from django.db import migrations, models
import django.db.models.deletion
import sevenoneseven.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('medida', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=10)),
                ('precio', models.IntegerField()),
                ('descripcion', models.CharField(max_length=500)),
                ('cantidad', models.IntegerField()),
                ('peso', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='productos/')),
                ('tipo', models.IntegerField(choices=[(1, 'Camiseta'), (2, 'Pantalon'), (3, 'Gorra'), (4, 'Accesorio'), (5, '')], default=1)),
                ('gen', models.IntegerField(choices=[(1, 'Masculino'), (2, 'Femenino')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15, unique=True)),
                ('direccion', models.CharField(max_length=254)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=254)),
                ('fecha_nac', models.DateField(help_text='DD-MM-AAAA', validators=[sevenoneseven.models.validate_birth_date])),
                ('genero', models.IntegerField(choices=[(1, 'Masculino'), (2, 'Femenino'), (3, 'Otro')], default=3)),
                ('rol', models.IntegerField(choices=[(1, 'Admin'), (2, 'Empleado'), (3, 'Cliente')], default=3)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.IntegerField()),
                ('total', models.IntegerField()),
                ('fecha', models.DateTimeField(help_text='AAAA-MM-DD')),
                ('medioPago', models.IntegerField(choices=[(1, 'PSE'), (2, 'Tarjeta Credito'), (3, 'Tarjeta Debito'), (4, 'Efecty')], default=1)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk1_factura_cliente', to='sevenoneseven.usuario')),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk1_factura_empleado', to='sevenoneseven.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCompras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('subtotal', models.IntegerField()),
                ('talla', models.CharField(max_length=10)),
                ('precioProducto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sevenoneseven.producto')),
            ],
        ),
    ]
