# Generated by Django 4.0.6 on 2025-04-07 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sevenoneseven', '0002_remove_factura_empleado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallecompras',
            name='talla',
        ),
    ]
