# Generated by Django 4.0.6 on 2025-04-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevenoneseven', '0003_remove_detallecompras_talla'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecompras',
            name='talla',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
