# Generated by Django 4.0.6 on 2025-04-08 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sevenoneseven', '0005_productofactura'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallesFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('subtotal', models.IntegerField()),
                ('talla', models.CharField(max_length=10)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='sevenoneseven.factura')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sevenoneseven.producto')),
            ],
        ),
        migrations.RemoveField(
            model_name='productofactura',
            name='factura',
        ),
        migrations.DeleteModel(
            name='DetalleCompras',
        ),
    ]
