# Generated by Django 4.0.6 on 2025-04-08 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sevenoneseven', '0006_detallesfactura_remove_productofactura_factura_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleCompras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('subtotal', models.IntegerField()),
                ('talla', models.CharField(max_length=10)),
                ('precioProducto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sevenoneseven.producto')),
            ],
        ),
        migrations.RemoveField(
            model_name='detallesfactura',
            name='factura',
        ),
        migrations.RemoveField(
            model_name='detallesfactura',
            name='producto',
        ),
        migrations.DeleteModel(
            name='ProductoFactura',
        ),
        migrations.DeleteModel(
            name='DetallesFactura',
        ),
    ]
