# Generated by Django 4.0.6 on 2025-04-10 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sevenoneseven', '0007_detallecompras_remove_detallesfactura_factura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecompras',
            name='factura',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='sevenoneseven.factura'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='factura',
            name='medioPago',
            field=models.IntegerField(choices=[(1, 'PSE'), (2, 'Tarjeta Credito'), (3, 'Tarjeta Debito')], default=1),
        ),
    ]
