# Generated by Django 4.0.6 on 2025-04-10 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sevenoneseven', '0008_detallecompras_factura_alter_factura_mediopago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallecompras',
            name='factura',
        ),
    ]
