# Generated by Django 4.0.6 on 2025-04-10 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sevenoneseven', '0010_detallecompras_factura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallecompras',
            name='factura',
        ),
    ]
