# Generated by Django 4.0.6 on 2025-04-10 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sevenoneseven', '0011_remove_detallecompras_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecompras',
            name='factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='sevenoneseven.factura'),
        ),
    ]
